options("repos" = c(CRAN="http://mirrors.cloud.tencent.com/CRAN/"))

if (!require("tmle")) install.packages('tmle')
if (!require("CBPS")) install.packages('CBPS')
if (!require("grf")) install.packages('grf')
if (!require("WeightIt")) install.packages('WeightIt')
if (!require("foreach")) install.packages('foreach')
if (!require("SuperLearner")) install.packages('SuperLearner')
if (!require("survey")) install.packages('survey')
if (!require("ebal")) install.packages('ebal')
if (!require("ATE")) install.packages('ATE')
if (!require("optweight")) install.packages('optweight')
if (!require("dbarts")) install.packages('dbarts')
if (!require("bartCause")) install.packages('./dependencies/r/bartCause_source.tar.gz', repos=NULL, type="source")
